config/routes.rb
Rails.application.routes.draw do

  root to: "posts#index"

  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'
  
  resources :posts do
    resources :comments
  end

  resources :users do
    resources :posts
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  def author
    user.username
    # excellent use of a model method!
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # there is currently nothing restricting access to all actions, right?
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @user = User.find(session[:user]["id"])
    @post = Post.find(params[:post_id])
    @body = params.require(:comment).permit(:body)[:body]
    @comment = @user.comments.create(user: @user, post: @post, body: @body)
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @post = params[:post_id]
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
  # remember to use strong_params when possible
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
    # optionally, Post.where(user: session[:user])
  end
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @user = User.find(session[:user]["id"])
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end
  def update
    @post = Post.find(params[:id])
    # you can use a before action to set the @post instance variable.
    if @post.update(post_params)
      redirect_to @post
    else
      render :update
      # excellent!
    end
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_up
    @user = User.new
  end

  def sign_up!
    @user = User.new(params.require(:user).permit(:username, :password, :password_confirmation))
    if @user.save
      flash[:notice] = "Your account has been created!"
      redirect_to action: :sign_in

    else
      flash[:notice] = "Your account couldn't be created. Did you enter a unique username and password?"
      redirect_to action: :sign_up
    end
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      flash[:notice] = "This user doesn't exist!"
      redirect_to action: :sign_in
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])
      flash[:notice] = "Your password's wrong!"
      redirect_to action: :sign_in
    else
      flash[:notice] = "You're signed in, #{@user.username}!"
      session[:user] = @user
      redirect_to posts_path
    end
  end

  def sign_out
    flash[:notice] = "#{session[:user]["username"]} signed out!"
    session[:user] = nil
    redirect_to root_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<h4><%= comment.user.username + " said:" %></h4>
<p>
  <%= comment.body%><br>
</p>
<% if session[:user] && session[:user]["username"] == comment.user.username %>
  <%= link_to 'delete', [comment.post, comment], method: :delete %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]) do |f| %> <%# ran into issue when trying to display list of comments bellow because .build adds this comment to the collection with fields at nil %>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= ("Logged in as: " + session[:user]["username"]) if session[:user] %>
    <nav>
      <ul>
        <% if session[:user]%>
          <li><%= link_to "Sign Out", sign_out_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", sign_up_path %></li>
          <li><%= link_to "Sign In", sign_in_path %></li>
        <% end %>
      </ul>
    </nav>
    <h1><%= link_to "Scribble", posts_path %></h1>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
  </header>
  <main>

    <%= yield %>
  </main>
<footer>jsm</footer>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>

  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end  %>

app/views/posts/_post.html.erb
<!-- excellent use of a partial here!! ->
<h3><%= link_to post.title, post %></h3>
<p>
  <%= "by " + post.user.username %>
</p>
<p>
  <%= post.body %><br>
  <% if session[:user] && session[:user]["username"] == post.user.username %>
    <%= link_to "Edit", edit_post_path(post) %><br>
    <%= link_to "Delete", post_path(post), method: :delete %>
  <% end %>
</p>

app/views/posts/edit.html.erb
<%= render partial: "form" %>
<%= link_to @post.title, @post %><br>
<%= link_to "Destroy", @post, method: :delete %> <%#when 2nd argument was @post, post was being destroyed before @post = Post.find(params[:id] was executed) or not %>

app/views/posts/index.html.erb
<h2>Posts <%= (link_to "(+)", new_post_path) if session[:user] %></h2>

<%= render @posts %>

app/views/posts/new.html.erb
<%= render partial: "form" %>
<%= link_to "Back", posts_path %>

app/views/posts/show.html.erb
<%= render @post %>

<%= render @post.comments %> <%# had to put partial in comments views, expected it to go in post views %>

<% if session[:user] %>
<h3>New Comment</h3>
<%= render 'comments/form'%>
<% end %>

app/views/users/sign_in.html.erb
<h2>Sign In</h2>
<%= form_tag("/sign_in", method: "post") do %>
  <%= label_tag :username %><br>
  <%= text_field_tag :username %><br>

  <%= label_tag :password %><br>
  <%= password_field_tag :password %><br>
  <%= submit_tag "Sign In" %>
<% end %>

app/views/users/sign_up.html.erb
<h2>Sign Up</h2>
<%= form_for @user, url: {action: "sign_up"} do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Sign Up!" %>
<% end %>